repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: local
    hooks:
    -   id: eslint
        name: lint javascript / typescript
        language: system
        entry: npm run lint
        pass_filenames: false
-   repo: local
    hooks:
    -   id: prettier-check
        name: check prettier format
        language: system
        entry: npm run lint:format
        pass_filenames: false
